# backend/app/utils/constants.py
TASK_STATUS_CREATED = "CREATED"
TASK_STATUS_ASSIGNED = "ASSIGNED"
TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
TASK_STATUS_BLOCKED = "BLOCKED"
TASK_STATUS_RESOLVED = "RESOLVED"
TASK_STATUS_CLOSED = "CLOSED"

VALID_STATUS_TRANSITIONS = {
    TASK_STATUS_CREATED: [TASK_STATUS_ASSIGNED],
    TASK_STATUS_ASSIGNED: [TASK_STATUS_IN_PROGRESS],
    TASK_STATUS_IN_PROGRESS: [TASK_STATUS_BLOCKED, TASK_STATUS_RESOLVED],
    TASK_STATUS_BLOCKED: [TASK_STATUS_IN_PROGRESS],
    TASK_STATUS_RESOLVED: [TASK_STATUS_CLOSED],
    TASK_STATUS_CLOSED: [],
}

ACTIVE_STATUSES = [
    TASK_STATUS_ASSIGNED,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_BLOCKED,
]