apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      containers:
        - name: taskflow-backend
          image: taskflow-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000